name: CI
on:
  push:
    branches: [master-pipline]
    
  pull_request:
    branches: [master-pipline]
    
  workflow_dispatch:
  
  
jobs:
    build:
      runs-on: ubundu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Setup .NET Core SDK
           uses: actions/setup-dotnet@v3.0.3
           with:
               dotnet-version: 7.0.x   
         - name: Restore dependencies
           run: dotnet restore
         - name: Build
           run: dotnet build --no-restore
         - name: Test
           run: dotnet test
